python: can't open file 'run_automation.py': [Errno 2] No such file or directory
